// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "edgardanielgd123@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/check": {
            "post": {
                "description": "Checks against a RBAC policy if a user is allowed to access a resource.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access"
                ],
                "summary": "Check if resource is accessible by user",
                "parameters": [
                    {
                        "description": "Policies to check",
                        "name": "policies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/crud.AccessList-string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/grant": {
            "post": {
                "description": "Alters a RBAC policy to grant access to a resource.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access"
                ],
                "summary": "Grant access to resource",
                "parameters": [
                    {
                        "description": "Policies to grant",
                        "name": "policies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/crud.AccessList-string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/revoke": {
            "post": {
                "description": "Alters a RBAC policy to revoke access to a resource.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access"
                ],
                "summary": "Revoke access to resource",
                "parameters": [
                    {
                        "description": "Policies to revoke",
                        "name": "policies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/crud.AccessList-string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/update": {
            "post": {
                "description": "Alters a RBAC policy to update access to a resource.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access"
                ],
                "summary": "Update access to resource",
                "parameters": [
                    {
                        "description": "Policies to update",
                        "name": "policies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/crud.AccessListUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "crud.Access-string": {
            "type": "object",
            "required": [
                "actId",
                "resId",
                "usrId"
            ],
            "properties": {
                "actId": {
                    "type": "string"
                },
                "resId": {
                    "type": "string"
                },
                "usrId": {
                    "type": "string"
                }
            }
        },
        "crud.AccessList-string": {
            "type": "object",
            "properties": {
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/crud.Access-string"
                    }
                }
            }
        },
        "crud.AccessListUpdate": {
            "type": "object",
            "properties": {
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/crud.AccessUpdate"
                    }
                }
            }
        },
        "crud.AccessUpdate": {
            "type": "object",
            "required": [
                "new",
                "old"
            ],
            "properties": {
                "new": {
                    "$ref": "#/definitions/crud.Access-string"
                },
                "old": {
                    "$ref": "#/definitions/crud.Access-string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "",
	Description:      "UIdealist Authorization project API Docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
