basePath: /api
definitions:
  crud.AnonymousUserCreate:
    properties:
      temp_name:
        maxLength: 255
        type: string
    required:
    - temp_name
    type: object
  crud.TeamAddMember:
    properties:
      member_id:
        maxLength: 255
        type: string
      team_id:
        maxLength: 255
        type: string
      user_id:
        maxLength: 255
        type: string
    required:
    - member_id
    - team_id
    - user_id
    type: object
  crud.TeamCreate:
    properties:
      team_name:
        maxLength: 255
        type: string
      user_id:
        maxLength: 255
        type: string
    required:
    - team_name
    - user_id
    type: object
  crud.UserCreate:
    properties:
      email:
        maxLength: 255
        type: string
      username:
        maxLength: 255
        type: string
    required:
    - email
    - username
    type: object
info:
  contact:
    email: edgardanielgd123@gmail.com
    name: API Support
  description: Idealist project API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  version: "1.0"
paths:
  /v1/team:
    post:
      consumes:
      - application/json
      description: Create a new team
      parameters:
      - description: Team Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/crud.TeamCreate'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
      summary: Create a new team
      tags:
      - Team
  /v1/team/members/add:
    post:
      consumes:
      - application/json
      description: Add a member to a team
      parameters:
      - description: New member data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/crud.TeamAddMember'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
      summary: Create a new team
      tags:
      - Team
  /v1/user:
    post:
      consumes:
      - application/json
      description: Create a new user given username and email
      parameters:
      - description: User data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/crud.UserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
      summary: Create a new user
      tags:
      - User
  /v1/user/anonymous:
    post:
      consumes:
      - application/json
      description: Create a new user given username
      parameters:
      - description: Anonymous User Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/crud.AnonymousUserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
      summary: Create a new user
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
